spring:
  application:
    name: adapter
  datasource:
    url: jdbc:postgresql://postgres:5432/bk
    username: bk
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

server:
  port: 7000

# X-Road connection (for XROAD mode)
xroad:
#  # Prefer HTTPS interface of Security Server
#  ss-url: ${XROAD_SS_URL:https://ss2:8443}
#
#  # In test env SS uses self-signed certs -> allow turning TLS verification off
#  verify-tls: ${XROAD_VERIFY_TLS:false}
#
#  client: ${XROAD_CLIENT:DEV/ORG/BKTT/burokratt}
#  service: ${XROAD_SERVICE:DEV/ORG/CAD/cadastre/ehitis-andmed/v1}

  ss-url: https://ss2:8443
  verify-tls: false
  client-id-url: "EE/COM/10307231/10307231-xtehr"
  service-id-url: "EE/GOV/70003098/ehr3/ehitiseAndmeteParing/v1"
adapter:
  # DIRECT = call provider-service directly (works even if X-Road not fully configured)
  # XROAD  = call via Security Server using X-Road headers
  mode: ${ADAPTER_MODE:DIRECT}

  provider-base-url: ${PROVIDER_BASE_URL:http://provider-service:9000}
